ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of RPVMSSM_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_693 = ', GC_693
      WRITE(*,2) 'GC_695 = ', GC_695
      WRITE(*,2) 'GC_697 = ', GC_697
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_640 = ', GC_640
